--CREATE TABLE FND_CONC_REQ_SUMMARY_HIS AS SELECT * FROM FND_CONC_REQ_SUMMARY_V WHERE ROWNUM=0;
PROMPT ***RECORD COUNT SYSDATE -1***
SELECT COUNT(*) FROM FND_CONC_REQ_SUMMARY_HIS 
WHERE  TRUNC(REQUEST_DATE) = TRUNC(SYSDATE) - 1;

DELETE FROM FND_CONC_REQ_SUMMARY_HIS 
WHERE  TRUNC(REQUEST_DATE) = TRUNC(SYSDATE) - 1;

INSERT INTO FND_CONC_REQ_SUMMARY_HIS 
SELECT *
  FROM FND_CONC_REQ_SUMMARY_V
 WHERE TRUNC(REQUEST_DATE) = TRUNC(SYSDATE) - 1
   AND PHASE_CODE = 'C'
   AND STATUS_CODE = 'C';
COMMIT;