prompt Importing table APPS.Fnd_Menu_Entries_L4...
drop table apps.FND_MENU_ENTRIES_L4;
-- Create table
create table apps.FND_MENU_ENTRIES_L4
(
  user_menu_name       VARCHAR2(80) not null,
  entry_sequence       NUMBER not null,
  prompt               VARCHAR2(60),
  menu_id              NUMBER,
  sub_menu_name        VARCHAR2(80),
  menu_creation_date   DATE,
  sub_menu_description VARCHAR2(240),
  function_id          NUMBER,
  user_function_name   VARCHAR2(80),
  function_name        VARCHAR2(480),
  func_creation_date   DATE,
  user_function_desc   VARCHAR2(240),
  grant_flag           VARCHAR2(1) not null
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );

set feedback off
set define off
insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 1, 'Invoice Batches', 67702, 'AP_APXINWKB_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoice Workbench Functional Menu', 47204, 'EVN Invoice Batches', 'EVN_AP_APXINWKB', to_date('25-11-2012 03:08:13', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_AP: Invoice Batches', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 2, null, -1, null, null, null, 47786, 'EVN Invoice Batches (Standard)', 'AP_APXINWKB_BATCHES_STD', to_date('16-05-2014 08:43:20', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_AP: Invoice Batches (Standard)', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 3, 'Invoices', 67702, 'AP_APXINWKB_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoice Workbench Functional Menu', 1026, 'Invoices', 'AP_APXINWKB', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 4, null, -1, null, null, null, 1027, 'Invoices Summary', 'AP_APXINWKB_SUMMARY', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 5, 'Open Interface Invoices', -1, null, null, null, 3329, 'Open Interface Invoices', 'AP_APXIIFIX', to_date('26-08-1997 10:46:07', 'dd-mm-yyyy hh24:mi:ss'), null, 'N');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 6, null, -1, null, null, null, 12592, 'AP MRC Inquiry Window - Invoice', 'AP_MRC_IW_INVOICE', to_date('04-02-2002', 'dd-mm-yyyy'), 'Launch AP MRC Inquiry Window Invoice Page', 'N');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 7, 'Invoice Overview', -1, null, null, null, 1551, 'View Invoice Overview', 'AP_APXIWALL_VIEW', to_date('12-06-1997 14:59:12', 'dd-mm-yyyy hh24:mi:ss'), null, 'N');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_ENTRY_GUI12_L4', 8, 'Withheld Amounts', -1, null, null, null, 1352, 'Withheld Amounts', 'AP_APXTBCKT', to_date('12-06-1997 14:59:12', 'dd-mm-yyyy hh24:mi:ss'), null, 'N');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_GUI12_L4', 1, 'Entry', 86900, 'AP_INVOICES_ENTRY_GUI12_L4', to_date('06-10-2017 11:53:48', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoices Entry Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_GUI12_L4', 2, 'Inquiry', 86901, 'AP_INVOICES_INQUIRY_GUI12_L4', to_date('06-10-2017 12:02:22', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoices Inquiry Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_INQUIRY_GUI12_L4', 1, 'Invoice Batches', 67715, 'AP_APXINWKB_VIEW_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP View Invoice Workbench Functional Menu', 1031, 'View Invoice Batches Summary', 'AP_APXINWKB_BATCH_SUMMARY_VIEW', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_INVOICES_INQUIRY_GUI12_L4', 2, 'Invoices', 67715, 'AP_APXINWKB_VIEW_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP View Invoice Workbench Functional Menu', 1030, 'View Invoices Summary', 'AP_APXINWKB_SUMMARY_VIEW', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_PAYMENTS_ENTRY_GUI12_L4', 1, 'Payments', 67705, 'AP_APXPAWKB_CHECK_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP Payment Workbench Single Payment Functional Menu', 1025, 'Payments', 'AP_APXPAWKB', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_PAYMENTS_ENTRY_GUI12_L4', 2, 'EVN AP Payments', 67705, 'AP_APXPAWKB_CHECK_MENU', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP Payment Workbench Single Payment Functional Menu', 48336, 'EVN AP Payments', 'EVN_AP_APXPAWKB', to_date('11-09-2017 14:19:44', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AP_PAYMENTS_GUI12_L4', 1, 'Entry', 86902, 'AP_PAYMENTS_ENTRY_GUI12_L4', to_date('06-10-2017 12:07:16', 'dd-mm-yyyy hh24:mi:ss'), 'AP Payments Entry Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_RECEIPTS_GUI_L4', 1, 'Receipts', 68114, 'Receipts: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Receipt Workbench Functional Menu', 1844, 'Receipt', 'AR_ARXRWMAI_HEADER', to_date('18-02-1999 09:30:28', 'dd-mm-yyyy hh24:mi:ss'), 'FP_ARXRWMAI_WINDOW="RECEIPTS_DETAIL"', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_RECEIPTS_GUI_L4', 2, 'EVN AR Receipts', 68114, 'Receipts: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Receipt Workbench Functional Menu', 48356, 'EVN_AR_ARXRWMAI', 'EVN_AR_ARXRWMAI', to_date('20-09-2017 15:42:49', 'dd-mm-yyyy hh24:mi:ss'), 'FP_ARXRWMAI_WINDOW="RECEIPTS_DETAIL"', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 1, null, 68088, 'Transactions: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Transaction Workbench Functional Menu', 1691, 'Transactions', 'AR_ARXTWMAI_HEADER', to_date('13-11-1997 10:24:09', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 1.1, 'EVN Transaction', -1, null, null, null, 47846, 'EVN Transactions', 'EVN_AR_ARXTWMAI_HEADER', to_date('16-06-2014 11:18:43', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 1.2, null, -1, null, null, null, 47847, 'EVN Credit Transactions', 'EVN_ARXTWMAI', to_date('16-06-2014 11:27:18', 'dd-mm-yyyy hh24:mi:ss'), 'EVN Credit Transactions XXX', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 2, 'Declare Intercompany', -1, null, null, null, 47415, 'Declare Intercompany', 'AR_INTERNAL', to_date('03-06-2013 15:14:36', 'dd-mm-yyyy hh24:mi:ss'), 'Declare Intercompany XXX', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 3, 'Declare External', -1, null, null, null, 47443, 'Declare Extenal', 'AR_EXTERNAL', to_date('12-06-2013 14:47:39', 'dd-mm-yyyy hh24:mi:ss'), 'Declare Extenal XXX', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 4, 'Batches', 68088, 'Transactions: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Transaction Workbench Functional Menu', 1939, 'Transaction Batches', 'AR_ARXTWMAI_BATCH', to_date('12-06-1997 14:59:13', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 5, 'Batches Summary', 68088, 'Transactions: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Transaction Workbench Functional Menu', 1940, 'Transaction Batches Summary', 'AR_ARXTWMAI_BATCH_SUMMARY', to_date('13-11-1997 10:23:21', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 6, null, -1, null, null, null, 4405, 'XLA: View Accounting Lines', 'XLA_XLAIQACL', to_date('26-05-1999 16:17:31', 'dd-mm-yyyy hh24:mi:ss'), 'View Accounting Lines and T Accounts', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 7, null, 68088, 'Transactions: Subfunctions', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AR Transaction Workbench Functional Menu', 2017, 'Copy Transactions', 'AR_ARXTWMAI_COPY_FORM', to_date('13-11-1997 10:34:53', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('AR_TRANSACTIONS_GUI_L4', 8, null, -1, null, null, null, 25541, 'SLA: View Accounting - Lines Inquiries', 'XLA_LINESINQ_SUBLEDGER', to_date('02-06-2005', 'dd-mm-yyyy'), 'Subledger Accounting Journal Entry Lines Inquiries', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 2, 'Invoices', 86903, 'AP_INVOICES_GUI12_L4', to_date('06-10-2017 12:13:35', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoices Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 3, 'Payments', 86904, 'AP_PAYMENTS_GUI12_L4', to_date('06-10-2017 12:16:09', 'dd-mm-yyyy hh24:mi:ss'), 'AP Payments Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 20, 'Giao d?ch n?i b?', 86905, 'GL_SU_JOURNAL_L4', to_date('06-10-2017 12:20:58', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 120, 'Declare Intercompany', -1, null, null, null, 47415, 'Declare Intercompany', 'AR_INTERNAL', to_date('03-06-2013 15:14:36', 'dd-mm-yyyy hh24:mi:ss'), 'Declare Intercompany XXX', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 140, 'Khai báo d?i tu?ng khác', -1, null, null, null, 47926, 'Flexfield Values AP', 'FND_FNDFFMSV_AP', to_date('31-12-2014 14:49:41', 'dd-mm-yyyy hh24:mi:ss'), 'FlexField Segment Values Form  AP', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 145, 'Khai báo h?p d?ng AP', -1, null, null, null, 47966, 'Flexfield Values AP_PO', 'FND_FNDFFMSV_APPO', to_date('10-02-2015 11:45:30', 'dd-mm-yyyy hh24:mi:ss'), 'FlexField Segment Values Form', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AP_ACCOUNTANT_L4', 146, null, 70444, 'AP_ACCOUNTING_GUI12', to_date('01-04-1999 12:25:58', 'dd-mm-yyyy hh24:mi:ss'), 'AP Accounting Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 1, 'Transactions', 86906, 'AR_TRANSACTIONS_GUI_L4', to_date('06-10-2017 13:58:01', 'dd-mm-yyyy hh24:mi:ss'), 'AR_TRANSACTIONS_GUI_L4', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 2, 'Receipts', 86907, 'AR_RECEIPTS_GUI_L4', to_date('06-10-2017 14:14:47', 'dd-mm-yyyy hh24:mi:ss'), 'AR Receipts Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 3, 'Giao d?ch n?i b?', 86905, 'GL_SU_JOURNAL_L4', to_date('06-10-2017 12:20:58', 'dd-mm-yyyy hh24:mi:ss'), null, 47294, 'EVN Enter Journals', 'EVN_GL_GLXJEENT', to_date('22-01-2013 08:56:26', 'dd-mm-yyyy hh24:mi:ss'), '-- HiepDT', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 4, null, -1, null, null, null, 2849, 'Enter Journals: Post', 'GLXJEENT_P', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Post in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 5, null, -1, null, null, null, 2850, 'Enter Journals: Reverse', 'GLXJEENT_R', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Reverse in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 10, null, 70444, 'AP_ACCOUNTING_GUI12', to_date('01-04-1999 12:25:58', 'dd-mm-yyyy hh24:mi:ss'), 'AP Accounting Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_AR_ACCOUNTANT_L4', 140, 'EVN Find Transaction AR_GL', -1, null, null, null, 48166, 'EVN Find Transaction AR_GL', 'EVN_AR_GL_01_TT200', to_date('14-09-2016 16:47:28', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 1, 'Payment', 86068, 'EVN_CM_PAYMENT', to_date('13-12-2012 20:17:17', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 2, 'Receipt', 86069, 'EVN_CM_RECEIPT', to_date('13-12-2012 20:21:35', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 8, 'Define DFF', -1, null, null, null, 47455, 'EVN CM Declare DFF', 'CM_DFF', to_date('19-06-2013 13:58:43', 'dd-mm-yyyy hh24:mi:ss'), 'Declare CM XXX', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 10, 'Ðon v? c?p 2', -1, null, null, null, 47946, 'Flexfield Values CM', 'FND_FNDFFMSV_CM', to_date('20-01-2015 16:20:11', 'dd-mm-yyyy hh24:mi:ss'), 'FlexField Segment Values Form - Define Inter Company Value', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 11, 'Tax - Manual', -1, null, null, null, 47294, 'EVN Enter Journals', 'EVN_GL_GLXJEENT', to_date('22-01-2013 08:56:26', 'dd-mm-yyyy hh24:mi:ss'), '-- HiepDT', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 20, 'Define Bank Account', 79468, 'CE_BANK_ACCT_ADMIN', to_date('29-11-2005', 'dd-mm-yyyy'), 'Bank and account administration', 25578, 'Bank Account Maintenance', 'CE_ACCOUNT_SIMPLE', to_date('18-05-2006', 'dd-mm-yyyy'), 'Bank Account Maintenance', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 21, 'EVN ?y nhi?m chi', -1, null, null, null, 48168, 'EVN ?y Nhi?m Chi', 'EVN_CM_FND_UNCHI_TT200', to_date('28-09-2016 09:04:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CM_ACCOUNTANT_L4', 22, 'Define Receipt Method', -1, null, null, null, 1894, 'Receipt Classes', 'AR_ARXSUDRC', to_date('13-11-1997 12:27:41', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CO_ACCOUNTANT_L4', 1, 'Journals', 67902, 'GL_SU_JOURNAL', to_date('13-08-1997 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CO_ACCOUNTANT_L4', 3, 'Inquiry', 67901, 'GL_SU_INQUIRY', to_date('13-08-1997 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CO_ACCOUNTANT_L4', 6, 'Reports', 67907, 'GL_SU_REPORT', to_date('13-08-1997 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CO_ACCOUNTANT_L4', 31, 'Mapping FMIS and EBS', -1, null, null, null, 47250, 'GL Set Mapping FMIS and EBS', 'EVN_GL_INT_MAPPING', to_date('09-01-2013 17:44:17', 'dd-mm-yyyy hh24:mi:ss'), 'T?o quy t?c mapping don v? Fmis và EBS', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 1, 'Item Costs', 67554, 'CST_ITEM_COSTS', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Cost Item Costs', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 2, 'Supply Chain Costing', 71370, 'CST_SC_COSTING', to_date('11-10-2000 11:11:59', 'dd-mm-yyyy hh24:mi:ss'), 'Supply Chain Costing', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 3, 'Cost Mass Edits', 67810, 'CST_COST_INFO_MAIN', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Cost Information Maintenance', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 4, 'Periodic Costing', 69584, 'CST_PAC_MAIN', to_date('31-12-1998 10:36:44', 'dd-mm-yyyy hh24:mi:ss'), 'Periodic Average Costing', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 5, 'Accounting Close Cycle', 67772, 'INV_ACCOUNTING_CLOSE', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Accounting Close Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 6, 'Discrete Jobs', 67816, 'CST_DISCRETE_JOBS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Discrete Jobs', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 7, 'Accrual Write-Offs', 78749, 'CST_WRITE_OFF', to_date('26-04-2005', 'dd-mm-yyyy'), 'Accrual Write-Offs Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 8, 'View Transactions', 67800, 'CST_TRANSACTIONS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Cost Management Transaction Inquiries', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 9, 'Operational Analysis', 67812, 'CST_OPER_ANALYSIS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Operational Analysis', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 10, 'Business Intelligence', 71064, 'CST_BIS_MAIN', to_date('01-01-1980', 'dd-mm-yyyy'), 'BIS Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 11, 'Report', 67803, 'CST_REPORT', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Cost Management Reports', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 13, 'Requests', -1, null, null, null, 66, 'Concurrent Requests: View All (User Mode)', 'FND_FNDCPQCR_USER', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), 'Concurrent Requests: View User Mode Form', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 14, 'Change Organization', -1, null, null, null, 1153, 'Change Organization - CST', 'CST_CHGORG', to_date('12-06-1997 14:59:12', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 15, null, -1, null, null, null, 1135, 'Privilege to Maintain Cost', 'CST_MAINTAIN_COSTS', to_date('12-06-1997 14:59:11', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 16, null, -1, null, null, null, 1134, 'Privilege to View Cost', 'CST_VIEW_COST_INFORMATION', to_date('12-06-1997 14:59:11', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 17, 'SLA', 79293, 'CST_SLA_SUB_MENU', to_date('27-07-2005', 'dd-mm-yyyy'), 'SLA Sub Menu for Cost Management', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 18, 'COGS Recognition', 79294, 'COGS Recognition', to_date('14-06-2005', 'dd-mm-yyyy'), 'Revenue / COGS Matching Concurrent Request', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_CST_ACCOUNTANT_L4', 19, null, -1, null, null, null, 4405, 'XLA: View Accounting Lines', 'XLA_XLAIQACL', to_date('26-05-1999 16:17:31', 'dd-mm-yyyy hh24:mi:ss'), 'View Accounting Lines and T Accounts', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 1, 'Inquiry', 67520, 'FA_INQUIRY', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Inquiry menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 3, 'Assets', 67521, 'FA_TRANSACTION', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Transaction menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 4, 'Mass Additions', 67620, 'FA_MASS_ADDITIONS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Mass Additions menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 5, 'Mass Transactions', 67524, 'FA_MASS_TRX', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Mass Transaction menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 6, 'Production', 67626, 'FA_PRODUCTION', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Production menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 7, 'Depreciation', 67532, 'FA_DEPRN', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Depreciation menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 9, 'Tax', 67534, 'FA_TAX', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Tax menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 10, 'Budget', 67535, 'FA_BUDGET', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Budget menu for Oracle Assets', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 11, 'Physical Inventory', 68401, 'FA_INVENTORY', to_date('12-06-1997 15:04:26', 'dd-mm-yyyy hh24:mi:ss'), 'Physical Inventory Submenu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 12, 'Define Life Years', -1, null, null, null, 511, 'Depreciation Methods', 'FAXSUMET', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 13, 'Other', 67849, 'FND_OTHER 4.0', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Run reports, set profile options, and view concurrent processing for Forms 4.0', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 14, 'Purge', 67544, 'FA_PURGE', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Purge menu for Oracle Assets Administrator', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 15, 'Create Accounting', -1, null, null, null, 28034, 'Create Accounting', 'FAXSSCACCT', to_date('22-09-2005', 'dd-mm-yyyy'), 'Menu version of SRS Create Accounting', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 16, 'Reports', 86171, 'EVN_FA_REPORTS', to_date('06-05-2013 16:52:32', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 17, 'Define value set for category', -1, null, null, null, 47144, 'EVN Category Define', 'EVN_FA_C03', to_date('18-11-2012 21:06:27', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_FA_C03: EVN Category Define', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 900, 'EVN_FA_C01: Assets Workbench', -1, null, null, null, 47184, 'EVN Assets Workbench', 'EVN_FA_C01', to_date('25-11-2012 03:03:25', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_FA_C01: EVN Assets Workbench', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 902, 'EVN_FA_C02: EVN Retirements', -1, null, null, null, 47185, 'EVN Retirements', 'EVN_FA_C02_FA_FUN', to_date('25-11-2012 03:03:25', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_FA_C02: Gi?m tài s?n c? d?nh', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 903, 'EVN_FA_C04: EVN Unplanned Depreciation', -1, null, null, null, 47186, 'EVN Unplanned Depreciation', 'EVN_FA_C04', to_date('25-11-2012 03:03:25', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_FA_C04 (Kh?u hao b? sung tài s?n)', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_FA_ACCOUNTANT_L4', 910, 'EVN FA Hyperion Integrations', 86511, 'EVN_BU_FA_INT_MENU', to_date('23-04-2015 16:28:46', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_GL_ACCOUNTANT_L4', 1, 'Journals', 86905, 'GL_SU_JOURNAL_L4', to_date('06-10-2017 12:20:58', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_GL_ACCOUNTANT_L4', 3, 'Inquiry', 67901, 'GL_SU_INQUIRY', to_date('13-08-1997 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_GL_ACCOUNTANT_L4', 6, 'Reports', 67907, 'GL_SU_REPORT', to_date('13-08-1997 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_GL_ACCOUNTANT_L4', 8, 'EVN Thông tin chi nhánh', -1, null, null, null, 48275, 'EVN - Thông tin chi nhánh', 'EVN_SEGMENT2', to_date('20-07-2017 10:28:43', 'dd-mm-yyyy hh24:mi:ss'), 'THÔNG TIN CHI NHÁNH', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 5, 'Transactions', 67678, 'INV_TRANSACTIONS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Transaction Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 15, 'On-hand, Availability', 70635, 'INV_AVAILABILITY_OM', to_date('19-07-1999 13:39:16', 'dd-mm-yyyy hh24:mi:ss'), 'On-hand and Available Inventory', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 25, 'Costs', 67674, 'INV_COSTS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Cost Main Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 30, 'Counting', 67602, 'INV_COUNTING', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Cycle Counting, Physical Inventory, and Replenishment Counting Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 47, 'EVN Inventory Ending Balance', -1, null, null, null, 48189, 'EVN Inventory Ending Balance', 'EVN_INV_C18', to_date('14-10-2016 17:24:43', 'dd-mm-yyyy hh24:mi:ss'), 'EVN Inventory Ending Balance', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 55, 'Reports', 67825, 'INV_REPORTS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Reports Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 60, 'Requests', -1, null, null, null, 3770, 'View All Concurrent Requests for Inventory', 'INV_FNDCPQCR_USER', to_date('05-11-1997 14:30:24', 'dd-mm-yyyy hh24:mi:ss'), 'View All Concurrent Requests for Inventory', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 70, 'Change Organization', -1, null, null, null, 261, 'Change Organization - MRP', 'MRPCHORG', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'Change Organization', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 75, null, -1, null, null, null, 1640, 'Purchase Order Summary', 'PO_POXPOVPO', to_date('12-06-1997 14:59:13', 'dd-mm-yyyy hh24:mi:ss'), 'Users can view purchase order summary.', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 95, null, 70577, 'AZN_PR_INVENTORY', to_date('01-07-1999 09:49:17', 'dd-mm-yyyy hh24:mi:ss'), 'Graphical Process Navigator Menu for Inventory Processes', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 100, null, 70576, 'AZN_PR_ATO', to_date('01-07-1999 09:49:06', 'dd-mm-yyyy hh24:mi:ss'), 'Graphical Process Navigator Menu for Assemble to Order Process', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 110, null, 76014, 'E-signatures Process', to_date('07-09-2002', 'dd-mm-yyyy'), 'E-signatures Approval Process', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 115, null, 77044, 'Consigned Inventory Home Page', to_date('15-09-2003', 'dd-mm-yyyy'), 'Consigned Inventory Home Page', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 120, null, -1, null, null, null, 26674, 'Select Available Inventory', 'INVPCKLT_F', to_date('11-11-2004', 'dd-mm-yyyy'), 'Select Available Inventory', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 125, null, -1, null, null, null, 17739, 'WMS Rules Workbench', 'WMS_WMSRLWBF', to_date('26-11-2002', 'dd-mm-yyyy'), 'WMS Rules Workbench', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 130, null, -1, null, null, null, 16513, 'OPM QM Results View Function', 'GMDQRSLT_VIEW_F', to_date('10-02-2003', 'dd-mm-yyyy'), 'GMD QM Results View Function', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 135, null, -1, null, null, null, 440, 'View Quality Results', 'QARSINF', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 140, null, -1, null, null, null, 13250, 'Batch Step', 'GMESTPED_F', to_date('12-02-2002', 'dd-mm-yyyy'), 'Batch Steps', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 145, null, -1, null, null, null, 6861, 'Lot Genealogy', 'GMILTGEN_F', to_date('01-01-1980', 'dd-mm-yyyy'), 'Lot Genealogy', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 150, null, -1, null, null, null, 44418, 'View Message History', 'INV_INVMSHST', to_date('28-01-2010', 'dd-mm-yyyy'), 'View Message History', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 160, 'EVN Update Transactions', -1, null, null, null, 47194, 'EVN Update Transaction', 'EVN_INV_C01', to_date('25-11-2012 03:03:25', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_INV_C01: Update Transaction', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 200, 'LCM_Respond', 81838, 'LCM Main Menu', to_date('03-06-2008', 'dd-mm-yyyy'), 'LCM Main Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 202, 'Inquiry Journals', -1, null, null, null, 587, 'Journal Entry Inquiry', 'GLXIQJRN', to_date('26-02-1999 10:22:44', 'dd-mm-yyyy hh24:mi:ss'), 'Inquire on journal entries', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 210, null, 86409, 'EVN_INV_SETUP_CATEGORIES', to_date('11-12-2014 15:30:46', 'dd-mm-yyyy hh24:mi:ss'), 'Menu khai báo dành cho quy?n Manager', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 220, null, 86410, 'EVN_INV_INVSDSUB', to_date('12-12-2014 09:37:30', 'dd-mm-yyyy hh24:mi:ss'), 'EVN Menu cho Resp Manager d? don v? t? t?o SubInventory', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_ACCOUNTANT_L4', 230, 'Setup for Manager', 86909, 'EVN_INV_MAN_SETUP_L4', to_date('07-10-2017 10:37:27', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_INV_MAN_SETUP_L4', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_MAN_SETUP_L4', 10, 'Category Accounts', 86409, 'EVN_INV_SETUP_CATEGORIES', to_date('11-12-2014 15:30:46', 'dd-mm-yyyy hh24:mi:ss'), 'Menu khai báo dành cho quy?n Manager', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_MAN_SETUP_L4', 30, 'Account Aliases', -1, null, null, null, 1254, 'Account Aliases', 'INV_INVSDFAA', to_date('12-06-1997 14:59:12', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 1, 'Projects', 68269, 'Projects: Subfunctions', to_date('12-06-1997 15:04:26', 'dd-mm-yyyy hh24:mi:ss'), 'Projects Functional Menu', 2097, 'Projects', 'PA_PAXPREPR_PROJECT', to_date('12-06-1997 14:59:14', 'dd-mm-yyyy hh24:mi:ss'), 'Enter and maintain projects', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 5, 'Transactions', 67678, 'INV_TRANSACTIONS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Transaction Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 10, 'Move Orders', 69587, 'INV_MOVE_ORDER', to_date('09-03-1999 19:29:52', 'dd-mm-yyyy hh24:mi:ss'), 'Move Orders', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 15, 'On-hand, Availability', 70635, 'INV_AVAILABILITY_OM', to_date('19-07-1999 13:39:16', 'dd-mm-yyyy hh24:mi:ss'), 'On-hand and Available Inventory', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 16, 'Items', 67606, 'INV_ITEMS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Items Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 17, 'Costs', 67674, 'INV_COSTS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Cost Main Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 18, 'Counting', 67602, 'INV_COUNTING', to_date('12-06-1997 15:04:24', 'dd-mm-yyyy hh24:mi:ss'), 'Cycle Counting, Physical Inventory, and Replenishment Counting Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 21, 'Evn integration', 86209, 'EVN_INV_INT_MENU', to_date('03-07-2013 15:50:24', 'dd-mm-yyyy hh24:mi:ss'), 'Evn Inventory Integration Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 47, 'EVN Inventory Ending Balance', -1, null, null, null, 48189, 'EVN Inventory Ending Balance', 'EVN_INV_C18', to_date('14-10-2016 17:24:43', 'dd-mm-yyyy hh24:mi:ss'), 'EVN Inventory Ending Balance', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 55, 'Reports', 67825, 'INV_REPORTS', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Inventory Reports Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 60, 'Requests', -1, null, null, null, 3770, 'View All Concurrent Requests for Inventory', 'INV_FNDCPQCR_USER', to_date('05-11-1997 14:30:24', 'dd-mm-yyyy hh24:mi:ss'), 'View All Concurrent Requests for Inventory', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 70, 'Change Organization', -1, null, null, null, 261, 'Change Organization - MRP', 'MRPCHORG', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'Change Organization', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 75, null, -1, null, null, null, 1640, 'Purchase Order Summary', 'PO_POXPOVPO', to_date('12-06-1997 14:59:13', 'dd-mm-yyyy hh24:mi:ss'), 'Users can view purchase order summary.', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 80, 'Notification Summary', -1, null, null, null, 4849, 'Find Notifications', 'FND_WFNTF_FIND', to_date('16-03-1999 13:03:40', 'dd-mm-yyyy hh24:mi:ss'), 'Find Notifications', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 85, 'Workflow Monitor', -1, null, null, null, 4857, 'Find Processes', 'FND_WFMON', to_date('16-03-1999 13:03:40', 'dd-mm-yyyy hh24:mi:ss'), 'Find Processes', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 90, 'Notification List', -1, null, null, null, 759, 'ECO Approval Lists', 'ENG_ENGFDEAL', to_date('12-06-1997 14:59:11', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 95, null, 70577, 'AZN_PR_INVENTORY', to_date('01-07-1999 09:49:17', 'dd-mm-yyyy hh24:mi:ss'), 'Graphical Process Navigator Menu for Inventory Processes', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 100, null, 70576, 'AZN_PR_ATO', to_date('01-07-1999 09:49:06', 'dd-mm-yyyy hh24:mi:ss'), 'Graphical Process Navigator Menu for Assemble to Order Process', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 105, 'Workflow Background Engine', -1, null, null, null, 6032, 'Workflow Background Engine', 'INV_FNDRSRUN_WFBG', to_date('08-11-1999 17:04:19', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 110, null, 76014, 'E-signatures Process', to_date('07-09-2002', 'dd-mm-yyyy'), 'E-signatures Approval Process', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 115, null, 77044, 'Consigned Inventory Home Page', to_date('15-09-2003', 'dd-mm-yyyy'), 'Consigned Inventory Home Page', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 120, null, -1, null, null, null, 26674, 'Select Available Inventory', 'INVPCKLT_F', to_date('11-11-2004', 'dd-mm-yyyy'), 'Select Available Inventory', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 125, null, -1, null, null, null, 17739, 'WMS Rules Workbench', 'WMS_WMSRLWBF', to_date('26-11-2002', 'dd-mm-yyyy'), 'WMS Rules Workbench', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 130, null, -1, null, null, null, 16513, 'OPM QM Results View Function', 'GMDQRSLT_VIEW_F', to_date('10-02-2003', 'dd-mm-yyyy'), 'GMD QM Results View Function', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 135, null, -1, null, null, null, 440, 'View Quality Results', 'QARSINF', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 140, null, -1, null, null, null, 13250, 'Batch Step', 'GMESTPED_F', to_date('12-02-2002', 'dd-mm-yyyy'), 'Batch Steps', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 145, null, -1, null, null, null, 6861, 'Lot Genealogy', 'GMILTGEN_F', to_date('01-01-1980', 'dd-mm-yyyy'), 'Lot Genealogy', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 150, null, -1, null, null, null, 44418, 'View Message History', 'INV_INVMSHST', to_date('28-01-2010', 'dd-mm-yyyy'), 'View Message History', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 170, 'Invoice', 68011, 'AP_INVOICES_GUI12', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoices Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 200, 'LCM_Respond', 81838, 'LCM Main Menu', to_date('03-06-2008', 'dd-mm-yyyy'), 'LCM Main Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 201, 'Estimate Material', -1, null, null, null, 47195, 'EVN Estimate Material', 'EVN_INV_C05', to_date('25-11-2012 03:03:25', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_INV_C05: Estimate Material', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 202, 'Inquiry Journals', -1, null, null, null, 587, 'Journal Entry Inquiry', 'GLXIQJRN', to_date('26-02-1999 10:22:44', 'dd-mm-yyyy hh24:mi:ss'), 'Inquire on journal entries', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 210, null, 86409, 'EVN_INV_SETUP_CATEGORIES', to_date('11-12-2014 15:30:46', 'dd-mm-yyyy hh24:mi:ss'), 'Menu khai báo dành cho quy?n Manager', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_INV_TRANSACTION_L4', 220, 'Define Item/Subinventory Information', 86410, 'EVN_INV_INVSDSUB', to_date('12-12-2014 09:37:30', 'dd-mm-yyyy hh24:mi:ss'), 'EVN Menu cho Resp Manager d? don v? t? t?o SubInventory', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_LCM_ACCOUNTANT_L4', 5, null, 81836, 'LCM Home Page', to_date('05-06-2008', 'dd-mm-yyyy'), 'LCM Home Page', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_LCM_ACCOUNTANT_L4', 10, 'Workbench', 81834, 'LCM Workbench', to_date('03-06-2008', 'dd-mm-yyyy'), 'LCM Workbench', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_LCM_ACCOUNTANT_L4', 20, 'Other', 81837, 'LCM Other', to_date('21-10-2008', 'dd-mm-yyyy'), 'Run reports, set profile options, and view concurrent processing for Forms 4.0', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 1, 'Projects', 68269, 'Projects: Subfunctions', to_date('12-06-1997 15:04:26', 'dd-mm-yyyy hh24:mi:ss'), 'Projects Functional Menu', 2097, 'Projects', 'PA_PAXPREPR_PROJECT', to_date('12-06-1997 14:59:14', 'dd-mm-yyyy hh24:mi:ss'), 'Enter and maintain projects', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 2, 'Budgets', 68271, 'Budgets: Subfunctions', to_date('12-06-1997 15:04:26', 'dd-mm-yyyy hh24:mi:ss'), 'Budgets Functional Menu', 2099, 'Budgets', 'PA_PAXBUEBU', to_date('12-06-1997 14:59:14', 'dd-mm-yyyy hh24:mi:ss'), 'Enter budgets', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 2.1, 'EVN Total Estimate Cost Budget', -1, null, null, null, 47215, 'EVN Total Estimate Cost Budget', 'EVN_PM_01_PAXBUEBU', to_date('25-11-2012 03:08:13', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_PM_C03_C04: Total Estimate Cost Budget', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 2.2, 'EVN Capital Source Budget', -1, null, null, null, 47214, 'EVN Capital Source Budget', 'EVN_PM_01_02_PAXBUEBU', to_date('25-11-2012 03:08:13', 'dd-mm-yyyy hh24:mi:ss'), 'EVN_PM_C01: Capital Source Budget', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 2.4, 'EVN Budgets', -1, null, null, null, 47488, 'EVN Budgets', 'EVN_PM_C12', to_date('03-07-2013 14:15:02', 'dd-mm-yyyy hh24:mi:ss'), null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 3, 'Expenditures', 68242, 'PA_SU_EXPEND_GUI', to_date('01-01-1980', 'dd-mm-yyyy'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 5, 'Capitalization', 77759, 'PA_SU_CAPITAL_GUI', to_date('27-05-2003', 'dd-mm-yyyy'), null, 2105, 'Capital Projects', 'PA_PAXCARVW', to_date('12-06-1997 14:59:14', 'dd-mm-yyyy hh24:mi:ss'), 'Manage capital projects asset capitalization', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 7, 'Accounting Inquiries', 80046, 'Projects Subledger Accounting Inquiries', to_date('22-06-2006', 'dd-mm-yyyy'), 'Projects SLA Accounting Inquiries', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PM_ACCOUNTANT_L4', 17, 'Enter a Manual Journal', -1, null, null, null, 616, 'Enter Journals', 'GLXJEENT_A', to_date('12-06-1997 14:59:11', 'dd-mm-yyyy hh24:mi:ss'), 'Enter journals', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 5, 'Purchase Orders', 68059, 'Purchase Orders:', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Oracle Purchasing Purchase Orders Menu GUI', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 6, 'Invoice View', -1, null, null, null, 25720, 'Invoice View', 'POS_INVOICE_VIEW', to_date('16-05-2005', 'dd-mm-yyyy'), 'Invoice View Page', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 7, 'Receiving', 68061, 'Receiving:', to_date('12-06-1997 15:04:25', 'dd-mm-yyyy hh24:mi:ss'), 'Oracle Purchasing Receiving Menu GUI', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 14, 'Reports', 68339, 'Reports:', to_date('12-06-1997 15:04:26', 'dd-mm-yyyy hh24:mi:ss'), 'Oracle Purchasing Reports Menu GUI', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 15, 'Change Organization', -1, null, null, null, 261, 'Change Organization - MRP', 'MRPCHORG', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'Change Organization', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_PO_ACCOUNTANT_L4', 17, 'Requests', -1, null, null, null, 66, 'Concurrent Requests: View All (User Mode)', 'FND_FNDCPQCR_USER', to_date('12-06-1997 14:59:09', 'dd-mm-yyyy hh24:mi:ss'), 'Concurrent Requests: View User Mode Form', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_ACCOUNTANT_L4', 1, 'Invoices', 86903, 'AP_INVOICES_GUI12_L4', to_date('06-10-2017 12:13:35', 'dd-mm-yyyy hh24:mi:ss'), 'AP Invoices Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_ACCOUNTANT_L4', 5, 'Payments	', 86904, 'AP_PAYMENTS_GUI12_L4', to_date('06-10-2017 12:16:09', 'dd-mm-yyyy hh24:mi:ss'), 'AP Payments Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_ACCOUNTANT_L4', 10, 'Intercompay', 86908, 'EVN_TAX_GL_SU_JOURNAL_L4', to_date('07-10-2017 08:33:36', 'dd-mm-yyyy hh24:mi:ss'), null, -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_ACCOUNTANT_L4', 299, 'Transactions', 86906, 'AR_TRANSACTIONS_GUI_L4', to_date('06-10-2017 13:58:01', 'dd-mm-yyyy hh24:mi:ss'), 'AR_TRANSACTIONS_GUI_L4', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_ACCOUNTANT_L4', 300, null, 70444, 'AP_ACCOUNTING_GUI12', to_date('01-04-1999 12:25:58', 'dd-mm-yyyy hh24:mi:ss'), 'AP Accounting Menu', -1, null, null, null, null, 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_GL_SU_JOURNAL_L4', 1, 'Enter', -1, null, null, null, 616, 'Enter Journals', 'GLXJEENT_A', to_date('12-06-1997 14:59:11', 'dd-mm-yyyy hh24:mi:ss'), 'Enter journals', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_GL_SU_JOURNAL_L4', 2, null, -1, null, null, null, 2849, 'Enter Journals: Post', 'GLXJEENT_P', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Post in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('EVN_TAX_GL_SU_JOURNAL_L4', 3, null, -1, null, null, null, 2850, 'Enter Journals: Reverse', 'GLXJEENT_R', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Reverse in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 1, 'Enter', -1, null, null, null, 47294, 'EVN Enter Journals', 'EVN_GL_GLXJEENT', to_date('22-01-2013 08:56:26', 'dd-mm-yyyy hh24:mi:ss'), '-- HiepDT', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 9, null, -1, null, null, null, 583, 'Budgetary Control Transactions', 'GLXIQBCT', to_date('12-06-1997 14:59:10', 'dd-mm-yyyy hh24:mi:ss'), 'Inquire on budgetary control transactions', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 10, null, -1, null, null, null, 2849, 'Enter Journals: Post', 'GLXJEENT_P', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Post in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 11, null, -1, null, null, null, 2850, 'Enter Journals: Reverse', 'GLXJEENT_R', to_date('22-07-1997 14:50:18', 'dd-mm-yyyy hh24:mi:ss'), 'Reverse in the Enter Journals or Enter Encumbrances forms', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 12, null, -1, null, null, null, 4384, 'Generate AutoAllocation', 'GLXALGEN', to_date('03-03-1999 10:55:26', 'dd-mm-yyyy hh24:mi:ss'), 'Enter parameters to generate AutoAllocation requests', 'Y');

insert into APPS.Fnd_Menu_Entries_L4 (USER_MENU_NAME, ENTRY_SEQUENCE, PROMPT, MENU_ID, SUB_MENU_NAME, MENU_CREATION_DATE, SUB_MENU_DESCRIPTION, FUNCTION_ID, USER_FUNCTION_NAME, FUNCTION_NAME, FUNC_CREATION_DATE, USER_FUNCTION_DESC, GRANT_FLAG)
values ('GL_SU_JOURNAL_L4', 13, null, -1, null, null, null, 4388, 'Generate AutoAllocation: Run AutoAllocation Request', 'GLXALGEN_S', to_date('03-03-1999 10:55:27', 'dd-mm-yyyy hh24:mi:ss'), 'Run AutoAllocation requests', 'Y');

commit;
prompt Done.